spring:
  codec:
    max-in-memory-size: -1 # unlimited
  data:
    mongodb:
      uri: ${MONGODB_URI:}
  security:
    oauth2:
      resourceserver:
        jwt:
          key-value: pXjg7MSyU2biZtVj52K4lJPT9eXe4fmejgVUYfaFJPI=
server:
  port: ${PORT:8080} # Heroku dynamic port
