spring:
  codec:
    max-in-memory-size: -1 # unlimited
  data:
    mongodb:
      uri: ${MONGODB_URI:}
  messages:
    fallback-to-system-locale: false # use un-suffixed file
  security:
    oauth2:
      resourceserver:
        jwt:
          key-value: pXjg7MSyU2biZtVj52K4lJPT9eXe4fmejgVUYfaFJPI=
server:
  port: ${PORT:8080} # Heroku dynamic port
  error:
    include-message: always

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
