name: CI

on: [push]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - working-directory: ./meet-all-api
        run: mvn -B package
      - working-directory: ./meet-all-api
        run: docker build . -t pinguet62/meet-all-api
      - if: github.ref == 'refs/heads/master'
        working-directory: ./meet-all-api
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          docker tag pinguet62/meet-all-api registry.heroku.com/meet-all-api/web
          docker push registry.heroku.com/meet-all-api/web
          heroku container:release web --app meet-all-api
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - working-directory: ./meet-all-ui
        run: npm ci
      - working-directory: ./meet-all-ui
        run: npm run lint
      - working-directory: ./meet-all-ui
        env:
          CI: true
        run: npm run test
      - name: Upgrade Chrome to lastet version
        run: |
          sudo apt-get update
          sudo apt-get install google-chrome-stable
      - working-directory: ./meet-all-ui
        env:
          CI: true
        run: npm run e2e
      - working-directory: ./meet-all-ui
        run: npm run build -- --prod
      - working-directory: ./meet-all-ui
        run: docker build . -t pinguet62/meet-all-ui
      - if: github.ref == 'refs/heads/master'
        working-directory: ./meet-all-ui
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          docker tag pinguet62/meet-all-ui registry.heroku.com/meet-all-ui/web
          docker push registry.heroku.com/meet-all-ui/web
          heroku container:release web --app meet-all-ui
