name: CI

on: [push]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - working-directory: ./meet-all-api
        run: mvn -B package
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '8'
      - working-directory: ./meet-all-ui
        run: npm ci
      - working-directory: ./meet-all-ui
        run: npm run lint
      - working-directory: ./meet-all-ui
        env:
          CI: true
        run: npm run test
      - working-directory: ./meet-all-ui
        env:
          CI: true
        run: npm run e2e
      - working-directory: ./meet-all-ui
        run: npm run build
