name: CI

on: [ push ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./meet-all-api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'
      - run: mvn -B package
      - run: docker build . -t pinguet62/meet-all-api
      - if: github.ref == 'refs/heads/main'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          docker tag pinguet62/meet-all-api registry.heroku.com/meet-all-api/web
          docker push registry.heroku.com/meet-all-api/web
          heroku container:release web --app meet-all-api
  build-ui:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./meet-all-ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm ci
      - run: npm run lint
      - env:
          CI: true
        run: npm run test
      - name: Upgrade Chrome to lastet version
        run: |
          sudo apt-get update
          sudo apt-get install google-chrome-stable
      - env:
          CI: true
        run: npm run e2e
      - run: npm run build
      - run: docker build . -t pinguet62/meet-all-ui
      - if: github.ref == 'refs/heads/main'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
          docker tag pinguet62/meet-all-ui registry.heroku.com/meet-all-ui/web
          docker push registry.heroku.com/meet-all-ui/web
          heroku container:release web --app meet-all-ui
